language: node_js

node_js:
    - node

install:
    - npm install -g istanbul
    - npm install

before_script:
    - cd $TRAVIS_BUILD_DIR

script:
    - npm run test

after_success:
    - npm run coveralls